# Generated by Django 3.0.2 on 2020-03-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0002_recipe_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='date',
            new_name='posted_date',
        ),
    ]
