# Generated by Django 3.0.2 on 2020-03-30 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0003_auto_20200331_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='posted_date',
            new_name='date',
        ),
    ]
