# Generated by Django 3.0.2 on 2020-04-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0004_auto_20200331_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='memo',
            field=models.TextField(blank=True, max_length=1000, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=20, verbose_name='レシピ名'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='site',
            field=models.CharField(blank=True, max_length=2048, verbose_name='参考サイト'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('スープ', 'スープ'), ('ご飯', 'ご飯'), ('おかず', 'おかず')], max_length=20, verbose_name='種類'),
        ),
    ]
