# Generated by Django 3.0.2 on 2020-04-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0005_auto_20200403_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.CharField(max_length=200, verbose_name='材料'),
        ),
    ]
