# Generated by Django 3.0.2 on 2020-04-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, upload_to='Media', verbose_name='アイコン'),
        ),
    ]
